# Generated by Django 4.2.1 on 2023-05-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usercsv_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercsv',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
    ]
